/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessTransfer: typeof import('./src/components/AccessTransfer.vue')['default']
    AlienSpinner: typeof import('./src/components/AlienSpinner.vue')['default']
    BallBounceSpinner: typeof import('./src/components/BallBounceSpinner.vue')['default']
    BanterSpinner: typeof import('./src/components/BanterSpinner.vue')['default']
    CubeRotationSpinner: typeof import('./src/components/CubeRotationSpinner.vue')['default']
    DotSpinner: typeof import('./src/components/DotSpinner.vue')['default']
    GitHub: typeof import('./src/components/GitHub.vue')['default']
    InteractiveHoverButton: typeof import('./src/components/InteractiveHoverButton.vue')['default']
    LineRotationSpinner: typeof import('./src/components/LineRotationSpinner.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NHighlight: typeof import('naive-ui')['NHighlight']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NInputOtp: typeof import('naive-ui')['NInputOtp']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NWatermark: typeof import('naive-ui')['NWatermark']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AccessTransfer: typeof import('./src/components/AccessTransfer.vue')['default']
  const AlienSpinner: typeof import('./src/components/AlienSpinner.vue')['default']
  const BallBounceSpinner: typeof import('./src/components/BallBounceSpinner.vue')['default']
  const BanterSpinner: typeof import('./src/components/BanterSpinner.vue')['default']
  const CubeRotationSpinner: typeof import('./src/components/CubeRotationSpinner.vue')['default']
  const DotSpinner: typeof import('./src/components/DotSpinner.vue')['default']
  const GitHub: typeof import('./src/components/GitHub.vue')['default']
  const InteractiveHoverButton: typeof import('./src/components/InteractiveHoverButton.vue')['default']
  const LineRotationSpinner: typeof import('./src/components/LineRotationSpinner.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NColorPicker: typeof import('naive-ui')['NColorPicker']
  const NDivider: typeof import('naive-ui')['NDivider']
  const NDrawer: typeof import('naive-ui')['NDrawer']
  const NDrawerContent: typeof import('naive-ui')['NDrawerContent']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NDynamicTags: typeof import('naive-ui')['NDynamicTags']
  const NEmpty: typeof import('naive-ui')['NEmpty']
  const NFlex: typeof import('naive-ui')['NFlex']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NHighlight: typeof import('naive-ui')['NHighlight']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NImage: typeof import('naive-ui')['NImage']
  const NInput: typeof import('naive-ui')['NInput']
  const NInputNumber: typeof import('naive-ui')['NInputNumber']
  const NInputOtp: typeof import('naive-ui')['NInputOtp']
  const NLayout: typeof import('naive-ui')['NLayout']
  const NLayoutContent: typeof import('naive-ui')['NLayoutContent']
  const NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
  const NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
  const NLayoutSider: typeof import('naive-ui')['NLayoutSider']
  const NMenu: typeof import('naive-ui')['NMenu']
  const NModal: typeof import('naive-ui')['NModal']
  const NScrollbar: typeof import('naive-ui')['NScrollbar']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NSwitch: typeof import('naive-ui')['NSwitch']
  const NTag: typeof import('naive-ui')['NTag']
  const NWatermark: typeof import('naive-ui')['NWatermark']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}