/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    BaseAppBar: typeof import('./src/components/BaseAppBar.vue')['default']
    Blank: typeof import('./src/layouts/blank.vue')['default']
    Code: typeof import('./src/components/Code.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    DefineInput: typeof import('./src/components/DefineInput.vue')['default']
    FullScreenTapEffects: typeof import('./src/components/FullScreenTapEffects.vue')['default']
    GitHub: typeof import('./src/components/GitHub.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HorizontalLayout: typeof import('./src/layouts/Components/HorizontalLayout.vue')['default']
    Logo: typeof import('./src/layouts/Components/Logo.vue')['default']
    MagicalEffects: typeof import('./src/components/MagicalEffects.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NotivueProvider: typeof import('./src/components/NotivueProvider.vue')['default']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterEntry: typeof import('./src/components/RouterEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/layouts/Components/SideBar.vue')['default']
    SideBarMenu: typeof import('./src/layouts/Components/SideBarMenu.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    ToggleDarkMode: typeof import('./src/layouts/Components/ToggleDarkMode.vue')['default']
    ToggleFullScreen: typeof import('./src/layouts/Components/ToggleFullScreen.vue')['default']
    ToggleLanguage: typeof import('./src/layouts/Components/ToggleLanguage.vue')['default']
    ToolBar: typeof import('./src/layouts/Components/ToolBar.vue')['default']
    TooltipButton: typeof import('./src/components/TooltipButton.vue')['default']
    UserInfo: typeof import('./src/layouts/Components/UserInfo.vue')['default']
    VerticalLayout: typeof import('./src/layouts/Components/VerticalLayout.vue')['default']
    Vue3_3Demo: typeof import('./src/components/Vue3_3Demo.vue')['default']
    VueUseMotion: typeof import('./src/components/VueUseMotion.vue')['default']
  }
}
