/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/401': RouteRecordInfo<'/401', '/401', Record<never, never>, Record<never, never>>,
    '/composables/': RouteRecordInfo<'/composables/', '/composables', Record<never, never>, Record<never, never>>,
    '/composables/_': RouteRecordInfo<'/composables/_', '/composables/_', Record<never, never>, Record<never, never>>,
    '/composables/use-ai-editor': RouteRecordInfo<'/composables/use-ai-editor', '/composables/use-ai-editor', Record<never, never>, Record<never, never>>,
    '/composables/use-echart': RouteRecordInfo<'/composables/use-echart', '/composables/use-echart', Record<never, never>, Record<never, never>>,
    '/composables/use-emoji-picker': RouteRecordInfo<'/composables/use-emoji-picker', '/composables/use-emoji-picker', Record<never, never>, Record<never, never>>,
    '/composables/use-image-verify': RouteRecordInfo<'/composables/use-image-verify', '/composables/use-image-verify', Record<never, never>, Record<never, never>>,
    '/composables/use-naive-form': RouteRecordInfo<'/composables/use-naive-form', '/composables/use-naive-form', Record<never, never>, Record<never, never>>,
    '/composables/use-shiki': RouteRecordInfo<'/composables/use-shiki', '/composables/use-shiki', Record<never, never>, Record<never, never>>,
    '/directives': RouteRecordInfo<'/directives', '/directives', Record<never, never>, Record<never, never>>,
    '/example/': RouteRecordInfo<'/example/', '/example', Record<never, never>, Record<never, never>>,
    '/example/_': RouteRecordInfo<'/example/_', '/example/_', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/super': RouteRecordInfo<'/super', '/super', Record<never, never>, Record<never, never>>,
    '/ui/': RouteRecordInfo<'/ui/', '/ui', Record<never, never>, Record<never, never>>,
    '/ui/_': RouteRecordInfo<'/ui/_', '/ui/_', Record<never, never>, Record<never, never>>,
    '/ui/avatar-cropper': RouteRecordInfo<'/ui/avatar-cropper', '/ui/avatar-cropper', Record<never, never>, Record<never, never>>,
    '/ui/chat-bubble': RouteRecordInfo<'/ui/chat-bubble', '/ui/chat-bubble', Record<never, never>, Record<never, never>>,
    '/ui/interactive-hover-button': RouteRecordInfo<'/ui/interactive-hover-button', '/ui/interactive-hover-button', Record<never, never>, Record<never, never>>,
    '/ui/spin': RouteRecordInfo<'/ui/spin', '/ui/spin', Record<never, never>, Record<never, never>>,
  }
}
