/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/401': RouteRecordInfo<
      '/401',
      '/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/directives': RouteRecordInfo<
      '/directives',
      '/directives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setting/': RouteRecordInfo<
      '/setting/',
      '/setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setting/org-tree': RouteRecordInfo<
      '/setting/org-tree',
      '/setting/org-tree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setting/role': RouteRecordInfo<
      '/setting/role',
      '/setting/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setting/user': RouteRecordInfo<
      '/setting/user',
      '/setting/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setting/workflow': RouteRecordInfo<
      '/setting/workflow',
      '/setting/workflow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setting/workflow-instance': RouteRecordInfo<
      '/setting/workflow-instance',
      '/setting/workflow-instance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setting/workflow-task': RouteRecordInfo<
      '/setting/workflow-task',
      '/setting/workflow-task',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/super': RouteRecordInfo<
      '/super',
      '/super',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/401.vue': {
      routes:
        | '/401'
      views:
        | never
    }
    'src/pages/directives.vue': {
      routes:
        | '/directives'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/setting/index.vue': {
      routes:
        | '/setting/'
      views:
        | never
    }
    'src/pages/setting/06_org-tree.vue': {
      routes:
        | '/setting/org-tree'
      views:
        | never
    }
    'src/pages/setting/02_role.vue': {
      routes:
        | '/setting/role'
      views:
        | never
    }
    'src/pages/setting/01_user.vue': {
      routes:
        | '/setting/user'
      views:
        | never
    }
    'src/pages/setting/03_workflow.vue': {
      routes:
        | '/setting/workflow'
      views:
        | never
    }
    'src/pages/setting/04_workflow-instance.vue': {
      routes:
        | '/setting/workflow-instance'
      views:
        | never
    }
    'src/pages/setting/05_workflow-task.vue': {
      routes:
        | '/setting/workflow-task'
      views:
        | never
    }
    'src/pages/super.vue': {
      routes:
        | '/super'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
