/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/[...all]',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/401': RouteRecordInfo<
      '/401',
      '/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/': RouteRecordInfo<
      '/composables/',
      '/composables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/use-echart': RouteRecordInfo<
      '/composables/use-echart',
      '/composables/use-echart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/use-naive-form': RouteRecordInfo<
      '/composables/use-naive-form',
      '/composables/use-naive-form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/directives': RouteRecordInfo<
      '/directives',
      '/directives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/super': RouteRecordInfo<
      '/super',
      '/super',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/401.vue': {
      routes:
        | '/401'
      views:
        | never
    }
    'src/pages/composables/index.vue': {
      routes:
        | '/composables/'
      views:
        | never
    }
    'src/pages/composables/02_use-echart.vue': {
      routes:
        | '/composables/use-echart'
      views:
        | never
    }
    'src/pages/composables/01_use-naive-form.vue': {
      routes:
        | '/composables/use-naive-form'
      views:
        | never
    }
    'src/pages/directives.vue': {
      routes:
        | '/directives'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/super.vue': {
      routes:
        | '/super'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
